version: 2

repo:
  public: js-sdk-common
  private: js-sdk-common-private

branches:
  - name: main
    description: 5.x
  - name: 4.x
  - name: 3.x

publications:
  - url: https://www.npmjs.com/package/launchdarkly-js-sdk-common
    description: npm

jobs:
  - docker:
      image: node:12-buster
    template:
      name: npm

documentation:
  gitHubPages: true
  title: LaunchDarkly Javascript SDK Core Components
